spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '23audrms'
    url: jdbc:mysql://34.64.213.199/teampu

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  data:
    redis:
      host: localhost
      password:
      port: 6379

  jwt:
    secret: FJDNSKN4329JHVUYV2413YGUVFIFDKBGFJTDGFKBEQRFKBJHDVKVFKJSDHLUGKUYTFYTDRTEUFTF

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace