spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'
    url: jdbc:mysql://localhost:13306/teampu

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  data:
    redis:
      host: localhost
      password:
      port: 16379

  jwt:
    secret: FJDNSKN4329JHVUYV2413YGUVFIFDKBGFJTDGFKBEQRFKBJHDVKVFKJSDHLUGKUYTFYTDRTEUFTF

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace