name: Deploy on GCP using kubernetes

on:
  push:
    branches: [ develop ]

permissions:
  contents: write

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # repo에 있는 파일들 self-host 머신에 복제 
      - name: Transport docker-compose.yaml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SECRET_ACCESS_KEY }}
          overwrite: true
          source: ./manifest/spring-redis.yml
          target: ~/spring-redis

      - name: Connect to AWS EC2 with SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SECRET_ACCESS_KEY }}
          script: sudo kubectl apply -f ~/spring-redis/spring-redis.yml
